FROM almalinux:9
ENV COURSE="DevOps" \
    PLACE="Bangalore" \
    DURATION="120HRS" 
ARG COURSE1="DevOps with AWS" \
    PLACE1="ITPL" \
    DURATION1="150HRS" 
RUN echo "Hi, course is:${COURSE}}, duration is:${DURATION1}, place is:${PLACE}}"
CMD ["sleep", "1000"]
